#!/usr/bin/env python3
"""大量匯入單字"""
import sys
sys.path.insert(0, '/home/deck/study/vocab_trainer')

from word_list import WORD_LIST, add_word

# 大量常用英文單字
words = [
    ("obvious", "明顯的"), ("obviously", "明顯地"), ("occasion", "場合"), ("occupy", "佔據"),
    ("occur", "發生"), ("ocean", "海洋"), ("October", "十月"), ("odd", "奇特的"),
    ("offend", "冒犯"), ("offer", "提供"), ("officer", "軍官"), ("official", "官方的"),
    ("often", "經常"), ("oil", "油"), ("okay", "好的"), ("old", "舊的"),
    ("online", "線上的"), ("only", "只有"), ("onto", "到...上"), ("open", "打開"),
    ("opera", "歌劇"), ("operate", "操作"), ("opinion", "意見"), ("opponent", "對手"),
    ("opportunity", "機會"), ("oppose", "反對"), ("opposite", "相反的"), ("option", "選項"),
    ("orange", "柳橙"), ("orbit", "軌道"), ("order", "順序"), ("ordinary", "普通的"),
    ("organ", "器官"), ("organic", "有機的"), ("organization", "組織"), ("organize", "組織"),
    ("origin", "起源"), ("original", "原始的"), ("other", "其他的"), ("otherwise", "否則"),
    ("ought", "應該"), ("our", "我們的"), ("ourselves", "我們自己"), ("outcome", "結果"),
    ("outdoor", "戶外的"), ("outer", "外部的"), ("outline", "大綱"), ("outside", "外部"),
    ("outstanding", "突出的"), ("oven", "烤箱"), ("over", "結束"), ("overall", "整體的"),
    ("overcome", "克服"), ("overseas", "海外的"), ("owe", "欠"), ("own", "自己的"),
    ("owner", "所有者"), ("ownership", "所有權"), ("oxygen", "氧"), ("pace", "步伐"),
    ("pack", "打包"), ("package", "包裹"), ("page", "頁面"), ("pain", "疼痛"),
    ("painful", "疼痛的"), ("paint", "油漆"), ("painter", "畫家"), ("painting", "畫"),
    ("pair", "一對"), ("palace", "皇宮"), ("pale", "蒼白的"), ("palm", "手掌"),
    ("pan", "平底鍋"), ("panel", "面板"), ("panic", "恐慌"), ("pants", "褲子"),
    ("paper", "紙"), ("parade", "遊行"), ("paragraph", "段落"), ("parallel", "平行的"),
    ("parent", "父母"), ("park", "公園"), ("parking", "停車"), ("part", "部分"),
    ("participant", "參與者"), ("participate", "參加"), ("particle", "粒子"), ("particular", "特定的"),
    ("partner", "夥伴"), ("party", "派對"), ("pass", "通過"), ("passage", "通道"),
    ("passenger", "乘客"), ("passion", "熱情"), ("passive", "被動的"), ("passport", "護照"),
    ("password", "密碼"), ("past", "過去"), ("paste", "黏貼"), ("patch", "補丁"),
    ("patent", "專利"), ("path", "小路"), ("patience", "耐心"), ("patient", "病人"),
    ("pattern", "模式"), ("pause", "暫停"), ("pavement", "人行道"), ("pay", "支付"),
    ("payment", "付款"), ("peace", "和平"), ("peaceful", "和平的"), ("peak", "高峰"),
    ("peasant", "農民"), ("peer", "同輩"), ("penalty", "刑罰"), ("pencil", "鉛筆"),
    ("penny", "一分"), ("pension", "養老金"), ("people", "人們"), ("per", "每"),
    ("percent", "百分比"), ("percentage", "百分比"), ("perception", "知覺"), ("perfect", "完美的"),
    ("perform", "執行"), ("performance", "表現"), ("perhaps", "或許"), ("period", "時期"),
    ("permanent", "永久的"), ("permission", "許可"), ("permit", "許可"), ("persist", "堅持"),
    ("person", "人"), ("personal", "個人的"), ("personality", "人格"), ("personnel", "人員"),
    ("perspective", "觀點"), ("persuade", "說服"), ("phase", "階段"), ("phenomenon", "現象"),
    ("philosopher", "哲學家"), ("philosophy", "哲學"), ("phone", "電話"), ("photo", "照片"),
    ("photograph", "照片"), ("photographer", "攝影師"), ("phrase", "片語"), ("physical", "身體的"),
    ("physician", "醫生"), ("physics", "物理"), ("piano", "鋼琴"), ("pick", "挑選"),
    ("picture", "圖片"), ("piece", "片"), ("pill", "藥丸"), ("pillar", "柱子"),
    ("pillow", "枕頭"), ("pilot", "飛行員"), ("pin", "針"), ("pine", "松樹"),
    ("pink", "粉紅色的"), ("pioneer", "先驅"), ("pipe", "管子"), ("pistol", "手槍"),
    ("pit", "坑"), ("pitch", "音高"), ("pity", "憐憫"), ("place", "地方"),
    ("plain", "平凡的"), ("plane", "飛機"), ("planet", "行星"), ("plant", "植物"),
    ("plastic", "塑膠"), ("plate", "盤子"), ("platform", "平台"), ("play", "玩"),
    ("player", "玩家"), ("pleasant", "愉快的"), ("please", "請"), ("pleased", "高興的"),
    ("pleasure", "愉快"), ("pledge", "誓言"), ("plenty", "豐富"), ("plot", "情節"),
    ("plug", "插頭"), ("plus", "加"), ("pocket", "口袋"), ("poem", "詩"),
    ("poet", "詩人"), ("poetry", "詩"), ("point", "點"), ("poison", "毒藥"),
    ("pole", "桿"), ("police", "警察"), ("policy", "政策"), ("polish", "磨光"),
    ("polite", "有禮貌的"), ("political", "政治的"), ("politician", "政治家"), ("politics", "政治"),
    ("poll", "投票"), ("pollute", "污染"), ("pollution", "污染"), ("pond", "池塘"),
    ("pool", "水池"), ("poor", "貧窮的"), ("pop", "流行的"), ("popular", "受歡迎的"),
    ("popularity", "受歡迎程度"), ("population", "人口"), ("pork", "豬肉"), ("port", "港口"),
    ("portable", "可攜式的"), ("porter", "搬運工"), ("portion", "部分"), ("portrait", "肖像"),
    ("pose", "姿勢"), ("position", "位置"), ("positive", "積極的"), ("possess", "擁有"),
    ("possession", "佔有"), ("possibility", "可能性"), ("possible", "可能的"), ("post", "郵政"),
    ("poster", "海報"), ("postpone", "延遲"), ("pot", "鍋"), ("potato", "馬鈴薯"),
    ("potential", "潛在的"), ("pound", "英鎊"), ("pour", "倒"), ("poverty", "貧窮"),
    ("powder", "粉末"), ("power", "力量"), ("powerful", "強大的"), ("practical", "實用的"),
    ("practice", "練習"), ("praise", "讚美"), ("pray", "祈禱"), ("prayer", "祈禱"),
    ("precious", "珍貴的"), ("precise", "精確的"), ("precisely", "精確地"), ("precision", "精確度"),
    ("predict", "預測"), ("prefer", "更喜歡"), ("preference", "偏好"), ("pregnant", "懷孕的"),
    ("prejudice", "偏見"), ("preliminary", "初步的"), ("premier", "總理"), ("premise", "前提"),
    ("preparation", "準備"), ("prepare", "準備"), ("presence", "存在"), ("present", "現在的"),
    ("presentation", "簡報"), ("preserve", "保存"), ("presidency", "總統任期"), ("president", "總統"),
    ("presidential", "總統的"), ("press", "按壓"), ("pressure", "壓力"), ("presume", "假設"),
    ("pretend", "假裝"), ("pretty", "漂亮的"), ("prevent", "防止"), ("previous", " previous"),
    ("price", "價格"), ("pride", "驕傲"), ("priest", "牧師"), ("primary", "主要的"),
    ("prime", "首要的"), ("primitive", "原始的"), ("prince", "王子"), ("princess", "公主"),
    ("principal", " principal"), ("principle", "原則"), ("print", "列印"), ("printer", "印表機"),
    ("prior", "優先的"), ("priority", "優先"), ("prison", "監獄"), ("prisoner", "囚犯"),
    ("privacy", "隱私"), ("private", "私人的"), ("privilege", "特權"), ("prize", "獎品"),
    ("probably", "或許"), ("probe", "探查"), ("problem", "問題"), ("procedure", "程序"),
    ("proceed", "繼續"), ("process", "過程"), ("processor", "處理器"), ("produce", "生產"),
    ("producer", "生產者"), ("product", "產品"), ("production", " production"), ("productive", "多產的"),
    ("profession", "職業"), ("professional", "專業的"), ("professor", "教授"), ("profit", "利潤"),
    ("profitable", "有利可圖的"), ("profound", "深刻的"), ("program", " program"), ("programming", "程式設計"),
    ("progress", "進步"), ("project", "專案"), ("prominent", "突出的"), ("promise", "承諾"),
    ("promoting", "促銷"), ("prompt", "迅速的"), ("pronounce", "發音"), ("proof", "證明"),
    ("proper", "適當的"), ("properly", "適當地"), ("property", "財產"), ("proposal", "提案"),
    ("propose", "提議"), ("prosecutor", "檢察官"), ("prospect", "前景"), ("prosperity", "繁榮"),
    ("protect", "保護"), ("protection", " protection"), ("protein", "蛋白質"), ("protest", " protest"),
    ("proud", "自豪的"), ("prove", "證明"), ("provide", "提供"), ("provider", "提供者"),
    ("province", "省"), ("provision", "規定"), ("psychology", "心理學"), ("pub", "酒吧"),
    ("public", "公共的"), ("publication", "出版物"), ("publicity", "宣傳"), ("publish", "出版"),
    ("publisher", "出版商"), ("pull", "拉"), ("pulse", "脈搏"), ("pump", "幫浦"),
    ("punch", "拳打"), ("pupil", "學生"), ("purchase", "購買"), ("pure", " pure"),
    ("purple", "紫色的"), ("purpose", "目的"), ("pursue", "追求"), ("push", "推"),
    ("put", "放置"), ("puzzle", "謎題"), ("qualify", "使合格"), ("quality", "品質"),
    ("quantity", "數量"), ("quarter", "四分之一"), ("queen", "女王"), ("query", "查詢"),
    ("quest", "探索"), ("question", "問題"), ("quick", "快的"), ("quickly", "快速地"),
    ("quiet", "安靜的"), ("quite", "相當"), ("quit", " quit"), ("quiz", "測驗"),
    ("quota", "配額"), ("quote", "引用"), ("rabbit", "兔子"), ("race", "種族"),
    ("racial", "人種的"), ("racism", "種族歧視"), ("rack", "架子"), ("radar", "雷達"),
    ("radiation", "辐射"), ("radical", "激進的"), ("radio", "廣播"), ("rage", "憤怒"),
    ("raid", "突擊"), ("rail", "鐵軌"), ("rain", "雨"), ("rainbow", "彩虹"),
    ("raise", "提高"), ("rally", "集會"), ("random", "隨機的"), ("range", "範圍"),
    ("rank", "等級"), ("rapid", "快速的"), ("rare", "罕見的"), ("rarely", "很少"),
    ("rat", "老鼠"), ("rate", "比率"), ("rather", "相當"), ("ratio", "比率"),
    ("rational", "理性的"), ("reach", "到達"), ("react", "反應"), ("reaction", "反應"),
    ("read", "閱讀"), ("reader", "讀者"), ("reading", " reading"), ("ready", " ready"),
    ("real", "真實的"), ("realistic", "現實的"), ("reality", "現實"), ("realize", "實現"),
    ("really", "真的"), ("realm", "領域"), ("reason", "理由"), ("reasonable", "合理的"),
    ("rebel", "叛徒"), ("recall", "回憶"), ("receive", "收到"), ("recent", " recent"),
    ("recently", "最近"), ("reception", "接待"), ("recipe", "食譜"), ("recognition", " recognition"),
    ("recognize", "認出"), ("recommend", "推薦"), ("record", " record"), ("recorder", "錄音機"),
    ("recording", " recording"), ("recover", "恢復"), ("recruit", "招募"), ("reduce", "減少"),
    ("reduction", " reduction"), ("refer", "提及"), ("reference", " reference"), ("reflect", "反映"),
    ("reflection", " reflection"), ("reform", "改革"), ("refuge", "庇護"), ("refugee", " refugee"),
    ("refuse", "拒絕"), ("regard", " regard"), ("regarding", "關於"), ("regardless", " regardless"),
    ("regime", "政權"), ("region", " region"), ("regional", " regional"), ("register", "註冊"),
    ("regret", "遺憾"), ("regular", " regular"), ("regularly", " regularly"), ("regulate", "規範"),
    ("regulation", " regulation"), ("reinforce", "加強"), ("reject", " reject"), ("relate", "相關"),
    ("related", " related"), ("relation", " relation"), ("relationship", " relationship"), ("relative", " relative"),
    ("relax", "放鬆"), ("release", "釋放"), ("relevant", "相關的"), ("reliable", "可靠的"),
    ("relief", " relief"), ("relieve", "減輕"), ("religion", "宗教"), ("religious", " religious"),
    ("reluctant", "不情願的"), ("rely", "依賴"), ("remain", "保持"), ("remaining", " remaining"),
    ("remark", "言論"), ("remarkable", "了不起的"), ("remedy", "療法"), ("remember", "記得"),
    ("remind", "提醒"), ("remote", "遙遠的"), ("remove", "移除"), ("render", "使得"),
    ("renew", "更新"), ("rent", "租金"), ("repair", "修理"), ("repeat", "重複"),
    ("replace", "替換"), ("reply", "回覆"), ("report", "報告"), ("reporter", "記者"),
    ("represent", "代表"), ("representative", " representative"), ("republic", "共和國"), ("reputation", "名譽"),
    ("request", "要求"), ("require", "需要"), ("requirement", " requirement"), ("rescue", "救援"),
    ("research", "研究"), ("researcher", "研究者"), ("reservation", "預訂"), ("reserve", "保留"),
    ("resident", "居民"), ("resign", "辭職"), ("resistance", " resistance"), ("resolution", "決議"),
    ("resolve", "解決"), ("resort", "度假村"), ("resource", "資源"), ("respect", "尊敬"),
    ("respectable", "值得尊敬的"), ("respectful", "恭敬的"), ("respective", "各自的"), ("respectively", "分別地"),
    ("respond", "回應"), ("response", "回應"), ("responsibility", "責任"), ("responsible", " responsible"),
    ("rest", " rest"), ("restaurant", "餐廳"), ("restore", "恢復"), ("restrict", "限制"),
    ("restriction", " restriction"), ("result", "結果"), ("retain", "保留"), ("retire", "退休"),
    ("retirement", "退休"), ("retreat", "撤退"), ("return", "返回"), ("reveal", "揭示"),
    ("revenue", "收入"), ("reverse", "顛倒"), ("review", "審查"), ("revise", "修訂"),
    ("revolution", "革命"), ("reward", "獎勵"), ("rhythm", "節奏"), ("rice", "米"),
    ("rich", "富有的"), ("rid", "擺脫"), ("ride", "騎"), ("rider", "騎手"),
    ("ridge", "山脊"), ("rifle", "步槍"), ("right", " right"), ("rigid", "僵硬的"),
    ("ring", "戒指"), ("riot", "暴動"), ("rise", "上升"), ("risk", "風險"),
    ("risky", "危險的"), ("ritual", "儀式"), ("rival", " rival"), ("river", "河"),
    ("road", "路"), ("roar", "咆哮"), ("robot", "機器人"), ("rock", "岩石"),
    ("rocket", "火箭"), ("rod", "竿"), ("role", "角色"), ("roll", "滾動"),
    ("romantic", "浪漫的"), ("roof", "屋頂"), ("room", "房間"), ("root", "根"),
    ("rope", "繩子"), ("rose", "玫瑰"), ("rotate", "旋轉"), ("rough", "粗糙的"),
    ("roughly", " roughly"), ("round", " round"), ("route", "路線"), ("routine", "例行公事"),
    ("row", "排"), ("royal", "皇家的"), ("rubber", "橡膠"), ("rubbish", "垃圾"),
    ("rude", "無禮的"), ("ruin", "毀滅"), ("rule", "規則"), ("ruler", "統治者"),
    ("rumor", "謠言"), ("run", "跑"), ("runner", " runner"), ("running", " running"),
    ("rural", "鄉村的"), ("rush", "衝"), ("ruthless", "無情的"), ("sacred", "神聖的"),
    ("sacrifice", "犧牲"), ("sad", "悲傷的"), ("sadness", "悲傷"), ("safe", "安全的"),
    ("safely", " safely"), ("safety", "安全"), ("sail", "航行"), ("sailor", "水手"),
    ("saint", "聖人"), ("salad", "沙拉"), ("salary", "薪水"), ("sale", "銷售"),
    ("salt", "鹽"), ("same", "相同的"), ("sample", "樣本"), ("sanction", "制裁"),
    ("sand", "沙子"), ("sandwich", "三明治"), ("satellite", "衛星"), ("satisfaction", "滿足"),
    ("satisfied", "滿意的"), ("satisfy", "滿足"), ("Saturday", "星期六"), ("sauce", "醬汁"),
    ("save", "節省"), ("saving", "儲蓄"), ("say", "說"), ("scale", "規模"),
    ("scan", "掃描"), ("scandal", "醜聞"), ("scared", "害怕的"), ("scatter", "散播"),
    ("scenario", "情境"), ("scene", "場景"), ("scenery", "風景"), ("scent", "氣味"),
    ("schedule", "時間表"), ("scheme", "計畫"), ("scholar", "學者"), ("scholarship", "獎學金"),
    ("school", "學校"), ("science", "科學"), ("scientific", " scientific"), ("scientist", "科學家"),
    ("scope", "範圍"), ("score", "分數"), ("scout", "偵察員"), ("scratch", "抓"),
    ("scream", "尖叫"), ("screen", "螢幕"), ("screw", "螺絲"), ("script", "腳本"),
    ("sculpture", "雕塑"), ("seal", "印章"), ("search", "搜尋"), ("season", "季節"),
    ("seat", "座位"), ("second", "第二"), ("secondary", " secondary"), ("secret", "秘密"),
    ("secretary", "秘書"), ("section", "部分"), ("sector", "部門"), ("secure", "安全的"),
    ("security", "安全"), ("seed", "種子"), ("seek", "尋找"), ("seem", "看起來"),
    ("segment", "段落"), ("seize", "抓住"), ("seldom", "很少"), ("select", "選擇"),
    ("selection", " selection"), ("self", "自己"), ("sell", "賣"), ("seller", " seller"),
    ("semester", "學期"), ("seminar", "研討會"), ("senate", "參議會"), ("senator", "參議員"),
    ("send", "發送"), ("senior", " senior"), ("sensation", "轟動"), ("sense", "感覺"),
    ("sensible", "明智的"), ("sensitive", "敏感的"), ("sentence", "句子"), ("separate", "分開"),
    ("separately", "分開地"), ("separation", "分離"), ("September", "九月"), ("sequence", "順序"),
    ("series", "系列"), ("serious", "嚴肅的"), ("seriously", " seriously"), ("servant", "僕人"),
    ("serve", "服務"), ("server", "伺服器"), ("service", "服務"), ("session", " session"),
    ("set", "設定"), ("setting", " setting"), ("settle", "解決"), ("settlement", " settlement"),
    ("seven", "七"), ("seventeen", "十七"), ("seventh", "第七"), ("severe", "嚴重的"),
    ("shade", "陰影"), ("shadow", "影子"), ("shake", "搖晃"), ("shall", "將要"),
    ("shallow", "淺的"), ("shame", "羞恥"), ("shape", "形狀"), ("share", "分享"),
    ("shareholder", "股東"), ("sharp", "鋒利的"), ("shed", "小屋"), ("sheet", "床單"),
    ("shelf", "架子"), ("shell", "殼"), ("shelter", "庇護所"), ("shift", " shift"),
    ("shine", "閃耀"), ("ship", "船"), ("shirt", "襯衫"), ("shock", " shock"),
    ("shoe", "鞋子"), ("shoot", "拍攝"), ("shop", "商店"), ("shopping", "購物"),
    ("shore", "岸邊"), ("short", " short"), ("shortage", "短缺"), ("shortly", " shortly"),
    ("shot", " shot"), ("should", " should"), ("shoulder", " shoulder"), ("shout", "喊叫"),
    ("show", "顯示"), ("shower", "淋浴"), ("shrink", "萎縮"), ("shut", "關閉"),
    ("sick", "生病的"), ("side", " side"), ("sight", "視力"), ("sign", " sign"),
    ("signal", "信號"), ("signature", "簽名"), ("significance", " significance"), ("significant", " significant"),
    ("silence", "沉默"), ("silent", "安靜的"), ("silently", " silently"), ("silk", "絲綢"),
    ("silly", "愚蠢的"), ("silver", "銀"), ("similar", "相似的"), ("similarly", " similarly"),
    ("simplicity", "簡單"), ("simplify", "簡化"), ("simply", " simply"), ("simulate", "模擬"),
    ("since", " since"), ("sincere", "誠懇的"), ("sincerely", "誠懇地"), ("sing", "唱歌"),
    ("singer", "歌手"), ("single", " single"), ("sink", "水槽"), ("sir", "先生"),
    ("sister", "姐妹"), ("site", "地點"), ("situation", "情況"), ("six", "六"),
    ("sixteen", "十六"), ("sixth", "第六"), ("sixty", "六十"), ("size", "大小"),
    ("sketch", "素描"), ("ski", "滑雪"), ("skill", "技能"), ("skin", "皮膚"),
    ("skip", "跳過"), ("skirt", "裙子"), ("skull", "頭骨"), ("slave", "奴隸"),
    ("slavery", "奴隸制"), ("sleep", "睡覺"), ("sleepy", "想睡的"), ("slice", "切片"),
    ("slide", "滑動"), ("slight", "輕微的"), ("slightly", " slightly"), ("slim", "苗條的"),
    ("slip", "滑倒"), ("slope", "山坡"), ("slow", "慢的"), ("slowly", " slowly"),
    ("small", "小的"), ("smart", "聰明的"), ("smash", "粉碎"), ("smell", "氣味"),
    ("smile", "微笑"), ("smoke", "煙"), ("smoking", "吸煙"), ("smooth", "光滑的"),
    ("smoothly", " smoothly"), ("snake", "蛇"), ("snap", "快照"), ("snow", "雪"),
    ("so", "所以"), ("soak", "浸泡"), ("soap", "肥皂"), ("sob", "哭泣"),
    ("soccer", "足球"), ("social", " social"), ("society", " society"), ("sociology", "社會學"),
    ("sock", "短襪"), ("socket", "插座"), ("sofa", "沙發"), ("soft", "柔軟的"),
    ("software", "軟體"), ("soil", "土壤"), ("solar", "太陽的"), ("soldier", "士兵"),
    ("sole", "唯一的"), ("solely", " solely"), ("solemn", "莊嚴的"), ("solid", "固體的"),
    ("solution", " solution"), ("solve", "解決"), ("some", "一些"), ("somebody", "有人"),
    ("somehow", "不知怎麼地"), ("someone", "有人"), ("something", "某事"), ("sometimes", "有時"),
    ("somewhat", "有點"), ("somewhere", "某處"), ("song", "歌曲"), ("soon", "很快"),
    ("sophisticated", "複雜的"), ("sore", "痛的"), ("sorry", "抱歉的"), ("sort", "種類"),
    ("soul", "靈魂"), ("sound", "聲音"), ("soup", "湯"), ("source", "來源"),
    ("south", "南方"), ("southern", "南方的"), ("space", "空間"), ("spare", "備用的"),
    ("spark", "火花"), ("speak", "說"), ("speaker", "演說者"), ("special", "特別的"),
    ("specialist", "專家"), ("species", "物種"), ("specific", "具體的"), ("specifically", " specifically"),
    ("specimen", "樣本"), ("speech", "演說"), ("speed", "速度"), ("spell", "拼寫"),
    ("spending", " spending"), ("sphere", "球體"), ("spice", "香料"), ("spider", "蜘蛛"),
    ("spin", "旋轉"), ("spirit", "精神"), ("spiritual", "精神的"), ("spite", "怨恨"),
    ("split", "分開"), ("spoil", "寵壞"), ("spoken", "說的"), ("sponsor", "贊助者"),
    ("spoon", "湯匙"), ("sport", "運動"), ("spot", "地點"), ("spouse", "配偶"),
    ("spread", "傳播"), ("spring", "春天"), ("spy", "間諜"), ("square", "廣場"),
    ("squeeze", "擠壓"), ("stability", "穩定性"), ("stable", "穩定的"), ("stack", "堆"),
    ("staff", "員工"), ("stage", "舞台"), ("stain", "污點"), ("stair", "樓梯"),
    ("stake", "賭注"), ("stamp", "郵票"), ("stand", "站立"), ("standard", "標準"),
    ("star", "星星"), ("stare", "盯著"), ("start", "開始"), ("state", "狀態"),
    ("statement", "聲明"), ("station", "車站"), ("statistic", "統計"), ("statistics", "統計"),
    ("statue", "雕像"), ("status", "地位"), ("stay", "停留"), ("steady", "穩定的"),
    ("steal", "偷"), ("steam", "蒸汽"), ("steel", "鋼"), ("steep", "陡峭的"),
    ("stem", "莖"), ("step", "步驟"), ("stick", "棒"), ("stiff", "僵硬的"),
    ("still", "仍然"), ("sting", "刺痛"), ("stir", "攪拌"), ("stock", "庫存"),
    ("stomach", "胃"), ("stone", "石頭"), ("stool", "凳子"), ("stop", "停止"),
    ("storage", "儲存"), ("store", "商店"), ("storm", "風暴"), ("story", "故事"),
    ("stove", "爐子"), ("straight", "直的"), ("strain", "緊張"), ("strange", "奇怪的"),
    ("stranger", "陌生人"), ("strap", "帶子"), ("straw", "稻草"), ("stream", "溪流"),
    ("street", "街道"), ("strength", "力量"), ("strengthen", "加強"), ("stress", " stress"),
    ("stretch", "伸展"), ("strict", "嚴格的"), ("stride", "大步"), ("strike", "罷工"),
    ("striking", "引人注目的"), ("string", "繩子"), ("strip", "條"), ("stripe", "條紋"),
    ("strive", "努力"), ("stroke", "中風"), ("strong", "強壯的"), ("strongly", " strongly"),
    ("structural", "結構的"), ("structure", "結構"), ("struggle", "掙扎"), ("stubborn", "固執的"),
    ("stuck", "卡住"), ("student", "學生"), ("studio", "工作室"), ("study", "學習"),
    ("stuff", "東西"), ("stumble", "絆倒"), ("stunning", "極美的"), ("stupid", "愚蠢的"),
    ("style", "風格"), ("subject", "主題"), ("submit", "提交"), ("subsequent", " subsequent"),
    ("substance", "物質"), ("substantial", " substantial"), ("substantially", " substantially"), ("substitute", " substitute"),
    ("suburb", "郊區"), ("succeed", "成功"), ("success", "成功"), ("successful", "成功的"),
    ("successfully", " successfully"), ("such", "這樣的"), ("sudden", "突然的"), ("suddenly", "突然地"),
    ("suffer", "遭受"), ("sufficient", "足夠的"), ("sugar", "糖"), ("suggest", "建議"),
    ("suggestion", "建議"), ("suicide", "自殺"), ("suit", "一套"), ("suitable", "合適的"),
    ("suite", "套房"), ("summary", "摘要"), ("summer", "夏天"), ("summit", "高峰"),
    ("sun", "太陽"), ("sunny", "晴朗的"), ("sunset", "日落"), ("sunshine", "陽光"),
    ("super", "超級的"), ("superb", "極好的"), ("superior", "較高的"), ("supermarket", "超級市場"),
    ("supervise", "監督"), ("supervision", "監督"), ("supplement", "補充"), ("supplier", "供應商"),
    ("supply", "供應"), ("support", "支持"), ("supporter", "支持者"), ("suppose", "假設"),
    ("supposed", " supposed"), ("supposedly", " supposedly"), ("suppress", "鎮壓"), ("supreme", "最高的"),
    ("sure", "確定的"), ("surely", " surely"), ("surface", "表面"), ("surgeon", "外科醫生"),
    ("surgery", "外科"), ("surname", "姓"), ("surplus", "盈餘"), ("surprise", "驚喜"),
    ("surprised", "吃驚的"), ("surprising", "令人驚訝的"), ("surprisingly", " surprisingly"), ("surround", "包圍"),
    ("surrounding", "周圍的"), ("surroundings", "環境"), ("survey", "調查"), ("survival", "生存"),
    ("survive", "存活"), ("survivor", "倖存者"), ("suspect", "嫌疑犯"), ("suspend", "暫停"),
    ("suspicion", "懷疑"), ("suspicious", "可疑的"), ("sustain", "維持"), ("swallow", "吞嚥"),
    ("swear", "發誓"), ("sweat", "汗"), ("sweep", "打掃"), ("sweet", "甜的"),
    ("swift", "快速的"), ("swim", "游泳"), ("swimming", "游泳"), ("swing", "擺動"),
    ("switch", "開關"), ("sword", "劍"), ("symbol", "符號"), ("sympathetic", "同情的"),
    ("sympathy", "同情"), ("syndrome", "症候群"), ("system", "系統"), ("systematic", "系統的"),
    ("table", "桌子"), ("tablet", "藥丸"), ("tackle", "處理"), ("tactic", "戰術"),
    ("tag", "標籤"), ("tail", "尾巴"), ("take", "拿"), ("tale", "故事"),
    ("talent", "才能"), ("talented", "有天賦的"), ("talk", "說話"), ("tall", "高的"),
    ("tank", "坦克"), ("tap", "輕敲"), ("tape", "膠帶"), ("target", "目標"),
    ("task", "任務"), ("taste", "味道"), ("tasty", "美味的"), ("tax", "稅"),
    ("taxi", "計程車"), ("tea", "茶"), ("teach", "教導"), ("teacher", "老師"),
    ("team", "團隊"), ("tear", "眼淚"), ("technical", "技術的"), ("technique", "技術"),
    ("technology", "科技"), ("teenager", "青少年"), ("teeth", "牙齒"), ("telephone", "電話"),
    ("television", "電視"), ("tell", "告訴"), ("temperature", "溫度"), ("temporary", "臨時的"),
    ("tend", "傾向"), ("tendency", "傾向"), ("tender", "溫柔的"), ("tennis", "網球"),
    ("tense", "緊張的"), ("tension", "張力"), ("tent", "帳篷"), ("term", "術語"),
    ("terminal", "終端"), ("terrible", "可怕的"), ("territory", "領土"), ("terror", "恐怖"),
    ("terrorism", "恐怖主義"), ("terrorist", "恐怖分子"), ("test", "測試"), ("testify", "作證"),
    ("testimony", "證詞"), ("text", "文字"), ("than",